### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by 5nyper** [sferik/twitter-crystal#2]
Hi, are there any examples using this library? maybe a simple script that tweets something :P

**Comment by seemsindie** [comment]
+1

**Comment by perks** [comment]
Yeah, would love to see best practices on going about building web API wrappers using crystal!

**Comment by piedoom** [comment]
I'm using this shard as a basis for my own library for the [Tumblr API](https://github.com/piedoom/tumblr-crystal).  I'm learning a ton about building wrappers in crystal, so I'll try and write something up if the maintainer doesn't get to it :).  Spoiler: OAuth in Crystal is painless and wonderful.

**Comment by kenta-s** [comment]
Now we have some examples in [README](https://github.com/sferik/twitter-crystal) I hope it will help.
