### ISSUE TITLE
Please keep releases up to date

### ISSUE THREAD

**Issue by vladfaust** [sferik/twitter-crystal#48]
Crystal shards heavily rely on releases. Having master branch in dependencies is a bad pattern.

**Comment by kenta-s** [comment]
Thank you. Going to release `0.2.0` somewhere around next week.

**Comment by vladfaust** [comment]
Will keep it open as a reminder for you :smile:

**Comment by veelenga** [comment]
Waiting for the release as well 👍 refs https://github.com/crystal-community/crystal-ann/pull/39

**Comment by kenta-s** [comment]
Just published `0.2.0`. 

@vladfaust 
https://github.com/sferik/twitter-crystal/pull/49 still remains open, but don't worry. I will keep releases up to date 😃
